name: Deploy staging

on:
  push:
    branches:
      - develop

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v2
      # possibly setup node action here...
      # possibly cache of node modules action here...
      # build steps here...
      - uses: akhileshhns/heroku-deploy@v3.12.12
        with:
          api_key: ${{secrets.HEROKU_API_KEY}}
          email: morvan.aurelien@gmail.com
          app_name: pricing-be
          appdir: "api"
